// pages/api/hellocoop.js
// generated by @hellocoop/quickstart --nextjs on 2024-11-20T13:00:42.539Z
// NOTE: this file should not need to be edited
import config from '../../hello.config'
import { pageAuth } from '@hellocoop/nextjs'
export default pageAuth(config)
